//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageProcessing.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_VIDEOSTITCH                 103
#define IDR_MAINFRAME                   128
#define IDR_IMAGEPTYPE                  129
#define IDD_CHAP2                       130
#define IDD_THRESHOLDING_DLG            131
#define IDD_CHAP3                       132
#define IDD_CHAP4                       133
#define IDD_CHAP5                       134
#define IDR_CONTEXT                     135
#define IDD_APPLICATION                 135
#define IDD_MAIN_PROCESS                136
#define IDD_YUV_OPT                     137
#define IDD_SAVE_SCREEN_OPT             138
#define IDD_IMAGESTITCH_JY              141
#define IDC_HISTOGRAM                   1000
#define IDC_THRESHOLD                   1001
#define IDC_OPERATION                   1001
#define IDC_THRESHOLD_VALUE             1002
#define IDC_CANCEL                      1003
#define IDC_REVERSE                     1004
#define IDC_THRESHOLDING                1005
#define IDC_THRESHOLDING_DLG            1006
#define IDC_MOVE                        1007
#define IDC_OPERATION_TYPE              1008
#define IDC_HISTOGRAM_EQ                1009
#define IDC_SCALE_X2                    1009
#define IDC_X0                          1010
#define IDC_MEAN                        1010
#define IDC_X1                          1011
#define IDC_Y0                          1011
#define IDC_WINDOW_SIZE                 1011
#define IDC_ROTATE                      1012
#define IDC_MEDIAN                      1012
#define IDC_H                           1012
#define IDC_DEG                         1013
#define IDC_SOBEL                       1013
#define IDC_LAPLACIAN                   1014
#define IDC_DITHERING                   1014
#define IDC_LAPLACIAN_SHARP             1015
#define IDC_DFT                         1016
#define IDC_LABELING                    1017
#define IDC_THINNING                    1018
#define IDC_FFT                         1019
#define IDC_LABELING_MOMENT             1019
#define IDC_DFT_ROW_COL                 1020
#define IDC_BPN                         1020
#define IDC_MEAN_SHIFT                  1020
#define IDC_FILTERING                   1021
#define IDC_FILTER_TYPE                 1022
#define IDC_FILTER_TYPE2                1023
#define IDC_DCT                         1023
#define IDC_N                           1024
#define IDC_COMPRESSION                 1024
#define IDC_DC                          1025
#define IDC_BLOCK_SIZE                  1025
#define IDC_UP_DOWN                     1026
#define IDC_BLOCK_SIZE2                 1026
#define IDC_FILE_NAME                   1026
#define IDC_PERCENT                     1027
#define IDC_THRESHOLDING_PTILE          1028
#define IDC_THRESHOLDING_VALLEY         1029
#define IDC_VEHICLE_RUN                 1029
#define IDC_THRESHOLDING_ITERATE        1030
#define IDC_FOLDER_SEL                  1030
#define IDC_HOUGH                       1031
#define IDC_LPR_RUN                     1031
#define IDC_AVI_RUN                     1031
#define IDC_TURTLE                      1032
#define IDC_FILE_SEL                    1032
#define IDC_YUV_RUN                     1032
#define IDC_K_COSINE                    1033
#define IDC_MOTION_RUN                  1033
#define IDC_K                           1034
#define IDC_BPN_EX                      1034
#define IDC_BPN_EX_RUN                  1034
#define IDC_FOLDER_NAME                 1035
#define IDC_DILATION                    1035
#define IDC_BIN                         1036
#define IDC_ELE_SIZE                    1037
#define IDC_SEL_FOLDER                  1037
#define IDC_SHAPE                       1038
#define IDC_DISP_FOLDER                 1038
#define IDC_EROSION                     1039
#define IDC_FILE_LIST                   1039
#define IDC_CLOSE                       1040
#define IDC_RUN                         1040
#define IDC_OPEN                        1041
#define IDC_START                       1041
#define IDC_END                         1042
#define IDC_PAUSE                       1043
#define IDC_GRAB                        1044
#define IDC_SEL_FOLDER2                 1045
#define IDC_DISP_FOLDER2                1046
#define IDC_GW                          1047
#define IDC_GH                          1048
#define IDC_VS                          1049
#define IDC_CAM_ON                      1050
#define IDC_TYPE                        1051
#define IDC_TYPE2                       1052
#define IDC_RESET_G_NUM                 1053
#define IDC_GAP                         1054
#define IDC_SLEEP                       1055
#define IDC_DISP_SLEEP                  1056
#define IDC_LIST                        1057
#define IDC_DISP_AVI                    1058
#define IDC_SEARCH                      1058
#define IDC_SEL_SOURCE                  1059
#define IDC_AVI_PAUSE                   1060
#define IDC_SOURCE_TYPE0                1060
#define IDC_SEL_AVI                     1061
#define IDC_YUV_TYPE0                   1061
#define IDC_GROW                        1061
#define IDC_SEL_YUV                     1062
#define IDC_YUV_TYPE1                   1062
#define IDC_MASK                        1062
#define IDC_SOURCE_TYPE1                1063
#define ID_CANCEL                       1063
#define IDC_SCALE_FORMAT0               1063
#define IDC_DISP_SOURCE                 1064
#define IDC_W                           1064
#define IDC_SOURCE_TYPE2                1065
#define IDC_SEQ_RUN                     1066
#define IDC_SCALE_FORMAT1               1066
#define IDC_ZOOM_SCALE0                 1066
#define IDC_TOTAL_FRAME                 1067
#define IDC_SCALE_FORMAT2               1067
#define IDC_SUB_FOLDER                  1068
#define IDC_SCALE_FORMAT3               1068
#define IDC_STEP                        1069
#define IDC_SEQ_TYPE                    1070
#define IDC_SAVE_SCREEN                 1071
#define IDC_BUTTON1                     1071
#define IDC_GetDualHomography           1071
#define IDC_SEL_SOURCE_L                1071
#define IDC_ZOOM_SCALE1                 1072
#define IDC_ZOOM_SCALE2                 1073
#define IDC_DETECTEDGE                  1073
#define IDC_ZOOM_SCALE3                 1074
#define IDC_VIEW_PSNR                   1075
#define IDC_GetSingleHomography         1075
#define IDC_RUN_TYPE0                   1076
#define IDC_GetSingleHomography2        1076
#define IDC_GetSingleAffine             1076
#define IDC_RUN_TYPE1                   1077
#define IDC_USE_COLOR_TYPE0             1078
#define IDC_USE_COLOR_TYPE1             1079
#define IDC_MEANSHIFT                   1079
#define IDC_PSNR_TYPE0                  1080
#define IDC_OCR                         1080
#define IDC_PSNR_TYPE1                  1081
#define IDC_EDITMINREGION               1081
#define IDC_PSNR_TYPE2                  1082
#define IDC_EDITMINFEATURE              1082
#define IDC_ME_GAP                      1083
#define IDC_MAXDIST                     1083
#define IDC_RUN_TYPE2                   1084
#define IDC_ONLYREGION                  1084
#define IDC_THRE_DIFF                   1085
#define IDC_EDITDILATION                1085
#define IDC_PARALLAXROBUST              1086
#define IDC_PARALLAXHANDLING            1087
#define IDC_CHECKFEATURE                1088
#define IDC_CHECKMATCHING               1089
#define IDC_CHECKLR                     1090
#define IDC_EDITMINAREA                 1092
#define IDC_MEAN_AUTO                   1094
#define IDC_EDIT_FEATURERATE            1095
#define IDC_EDIT_KL                     1096
#define IDC_EDIT_SIFT                   1097
#define IDC_EDIT_SEGREGIN               1098
#define IDC_DRAW                        1099
#define IDC_EDIT_DIFF                   1100
#define IDC_SEL_SOURCE_R                1100
#define IDC_DISP_SOURCEL                1101
#define IDC_DISP_SOURCER                1102
#define IDC_VIDEOSTITCH                 1103
#define IDM_GRAY_DUPLICATE              32771
#define IDM_COLOR_DUPLICATE             32772
#define IDM_CHAP2                       32773
#define IDM_CHAP3                       32774
#define IDM_SCALE_X2                    32775
#define IDM_SCALE_HALF                  32776
#define IDM_CHAP4                       32777
#define IDM_CHAP5                       32778
#define ID_FILE_OPEN_CUR                32779
#define IDM_APPLICATION                 32780
#define IDD_VIEW_MAIN_PROCESS           32781
#define IDM_SEL_REGION                  32782
#define IDM_SEL_REGION_ZOOM             32783
#define IDM_SUM                         32784
#define IDM_SUBTRACT                    32785
#define IDM_DIFFERENCE                  32786
#define ID_32787                        32787
#define IDM_IMAGESTITCH_JY              32788
#define ID_32789                        32789
#define IDM_VIDEOSTITCH                 32790

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
